language: python
python:
  - "3.5"

# command to install dependencies
install:
  - "pip install flake8"
  - "pip install -r requirements.txt"
  - "npm install -g bower"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - "cd kboard && python manage.py bower install && cd .."
  - "cd kboard && flake8 --exit-zero . && cd .."

# command to run tests
script:
  - cd kboard && coverage run --source=board manage.py test board/tests accounts/tests core/tests
  - python manage.py test functional_test/

after_success:
  - coveralls
  - cd docs; make html

notifications:
  email:
    - darjeeling@gmail.com
    - guswnsxodlf@gmail.com
    - cjh5414@gmail.com
