# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-20 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20161119_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedposthistory',
            name='ip',
            field=models.GenericIPAddressField(default='', null=True),
        ),
    ]
