# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-08 07:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20161007_0507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.Board'),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set([('board', 'title')]),
        ),
    ]
