# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20161010_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='content',
        ),
    ]
