# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-14 08:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20161013_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='slug',
            field=models.TextField(default='', unique=True),
        ),
    ]
