# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 04:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_post_is_delete'),
        ('board', '0008_board_slug'),
    ]

    operations = [
    ]
