# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 06:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20161022_2020'),
        ('board', '0010_auto_20161022_1515'),
    ]

    operations = [
    ]
