# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 11:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20161025_0119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='is_delete',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='is_delete',
            new_name='is_deleted',
        ),
    ]
