# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_edited_post_history'),
        ('board', '0013_TimeStampeModel modified_time'),
    ]

    operations = [
    ]
