# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-30 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_merge_20161031_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='editedposthistory',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='editedposthistory',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='editedposthistory',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.Post'),
        ),
        migrations.AddField(
            model_name='editedposthistory',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
