# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_auto_20161031_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
