# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_post_like_count'),
        ('board', '0016_post_file'),
    ]

    operations = [
    ]
