# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-09 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20161106_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='summernote',
            name='attachment_ptr',
        ),
        migrations.AddField(
            model_name='editedposthistory',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='SummerNote',
        ),
    ]
