# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0019_auto_20161109_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='pages_nav_chunk_size',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='board',
            name='posts_chunk_size',
            field=models.IntegerField(default=10),
        ),
    ]
