# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_attachment'),
        ('board', '0021_auto_20161110_2019'),
    ]

    operations = [
    ]
