# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0023_auto_20161111_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='comments_chunk_size',
            field=models.IntegerField(default=5),
        ),
    ]
