# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 02:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20161113_0118'),
        ('board', '0024_auto_20161111_2006'),
    ]

    operations = [
    ]
