# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-13 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_merge_20161113_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='editedPostHistory',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.EditedPostHistory'),
        ),
    ]
