# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 04:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_attachment_editedposthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editedposthistory',
            name='file',
        ),
    ]
