# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-14 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_remove_editedposthistory_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file',
        ),
    ]
