# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 08:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20161112_0325'),
        ('board', '0028_remove_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Account'),
        ),
    ]
