# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-15 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0029_comment_account'),
        ('board', '0029_post_account'),
    ]

    operations = [
    ]
