# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 09:36
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('created', 'Created'), ('deleted', 'Deleted')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=models.SET(accounts.models.get_sentinel_user), to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
