# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='created',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='updated',
            new_name='modified_time',
        ),
    ]
